### ISSUE TITLE
Obsolete extension library 

### ISSUE THREAD

**Issue by kaononymous** [tachiyomiorg/website#924] opened 2022-06-29 22:48 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Hi! My request is to have library on the extension website (not the app) with obsolete extensions

I currently use the Mangago extension in WebView. It helps me track manga that can only be found on mangago. You can still search and add manga to the library but you can't read within the app only through WebView.

My problem with mangago is that the website is only in desktop mode within WebView which makes it hard to navigate.

I am looking for the Manhuascan app/FM Reader app to use the same way. Even if it is in desktop mode it will be easier to navigate than mangago.

If you would prefer not to share these in a list, I am hoping I can get a copy of the manhuascan app.

**Comment by arkon** [comment] 2022-06-29 22:59
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12372

We don't support obsolete extensions.

**Closed by arkon** 2022-06-29 22:59 UTC
