### ISSUE TITLE
Extensions Not Showing

### ISSUE THREAD

**Issue by kiritoshi2002** [tachiyomiorg/website#613] opened 2021-04-25 13:26 UTC
Dear Tachiyomi Developers Recently for about 2 Days I can't find other extensions when I tried to refresh the below write texts are shown I tried this in 2 other phones but shows the same problem what can I do to solve this !!!!!!!

failed to connect to
raw.githubusercontent.com/ 185.199.109.133 (port 443) from / 25.88.162.191 (port 38208) after 30000ms

**Comment by Soitora** [comment] 2021-04-25 13:48
Are you unable to see extensions in the app's Extension list or is it in the website ([https://tachiyomi.org/extensions/](https://tachiyomi.org/extensions/))?

**Comment by arkon** [comment] 2021-04-25 13:53
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6697

**Comment by kiritoshi2002** [comment] 2021-04-25 14:01
I am facing problem both in the app and website what can I do?
I recently formated my phone so i am re adding my manga list but I can't
find and install even 1 extension only local source is available .when I
refresh a short message Is shown

failed to connect to

raw.githubusercontent.com/ 185.199.109.133 (port 443) from / 25.88.162.191
(port 38208) after

30000ms
How can I solve the issue ? Help plz

**Comment by Soitora** [comment] 2021-04-25 14:05
As the issue arkon linked to mentioned, try a  different network or a VPN; we can't really fix your connection issues.

**Comment by arkon** [comment] 2021-04-25 14:06
If you read the linked issue, I suggested using a VPN or another network.

**Closed** 2021-04-25 14:05 UTC
