### ISSUE TITLE
Add the option to hide categories

### ISSUE THREAD

**Issue by ivy21929** [tachiyomiorg/website#1084] opened 2023-11-14 08:22 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

That when entering the category section you can hide or see a category from the main menu again

**Comment by ghostbear** [comment] 2023-11-14 08:39
Wrong repository and duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/7757

**Closed** 2023-11-14 08:39 UTC
